### ISSUE TITLE
rinoh sphinx extension fails with sphinx 1.6+ due to default value resolution failures for paper size.

### ISSUE THREAD

**Issue by beeblebrox** [brechtm/rinohtype#114]
#Hi I found an issue with the sphinx rinoh extension when running on sphinx >= 1.6.  I did a bisect between release versions of sphinx and the regression occur from the last 1.5.6 release and 1.6 onward.

The symptom is that when trying to use the rinoh build target this error will occur:
`     AttributeError: No such config value: latex_paper_size`

This occurs even though I have tried `latex_paper_size = 'a4paper'`  and `latex_elements = {'papersize': 'a4paper'}`

By reverting back to 1.5.6 the rinoh front end is happy and works.

I debugged the issue briefly and it appears that in 1.6 the config object being passed into the setup step is only returning defaults, which is 'a4' for latex's papersize, in 1.6.  I think in 1.5 it was a4paper.  This results in the dict() conversion in rinoh to fail because it doesn't have the 'a4' key.  I don't the fix is to add the 'a4' key, read further to understand why.

As far as I can tell, at least with 1.6, that sphinx will not return override values from conf.py to the setup config object.  From what I can tell this is intended behavior making me believe that rinoh is making a bad assumption by relying on non default config values from latex to configure the default value for rinoh_paper_size.

Also, even if I set rinoh_paper_size manually in the config, the rinoh default setup will still trigger causing an error.  So, the only workaround I have found is reverting to sphinx 1.5.6. 

I think to get the desired behavior of using latex's values as the value for `rinoh_paper_size` the configuration for that value will need to be checked and set to latex's during the runtime, not setup, phase.  

## Here are the minimal reproducible steps for my environment:

Base environment is from conda using python 3.6.4.

### Install python 3.6.4, sphinx 1.6.6, and rinohtype 0.3.1

```  conda create -n simplecase
  conda install python (installs 3.6.4)
  pip install sphinx (installs sphinx-1.6.6)
  pip install rinohtype (installs rinohtype-0.3.1)
```

### Configure basic sphinx project
`sphinx-quickstart (using only defaults and project name/author name simple)`

Change extensions in the generated conf.py:
```
 extensions = ['rinoh.frontend.sphinx']
  latex_documents = [
      ('index', 'simple.tex', 'simple','simple', 'manual'),
  ]
  
  latex_elements = { 'papersize': 'a4paper' }
  #or latex_paper_size = 'a4paper', both have the issue
 #rinoh_paper_size = A4 does not prevent the default code from triggering for some reason.
```

### Build and Fail
`make rinoh`

This results in a failure:
```
  Exception occurred:
    File "c:\users\beebl\anaconda3\envs\simplecase\lib\site-packages\sphinx\config.py", line 309, in 
  __getattr__
      raise AttributeError(__('No such config value: %s') % name)
  AttributeError: No such config value: latex_paper_size
```
[sphinx-err-7pyb6l1k.log](https://github.com/brechtm/rinohtype/files/1649076/sphinx-err-7pyb6l1k.log)
Same results using sphinx-build.

### Workaround and Pass
```
pip install sphinx-1.5.6
make rinoh
```
This passes just fine.

**Comment by beeblebrox** [comment]
I'd like to repeat I think sphinx doesn't actually return the overridden values in 1.5 to the setup function of rinoh and that behavior did not change between 1.5 and 1.6.

I say this because instead of setting any of the latex papersize configurations to a4paper, in  sphinx 1.5, I can set them to garbage and rinoh still gets a4paper when looking up the value.  In 1.6 it nioh gets 'a4'.  I think the default for the latex papersize must have changed between 1.5 and 1.6 which has uncovered this issue with rinoh.

**Comment by brechtm** [comment]
Hi James. Thanks for the detailed analysis! My apologies for getting back to you so late.

I don't remember the details, but I think this issue has been fixed in the stable branch (751adc56aee632b361f27c641dbf89f3ac4a723f). I hope to make a new release soon, but don't have much time to work on rinohtype lately.

If you wish, you can install rinohtype from a checkout of the stable branch in the meantime. If you do, please confirm this fixes the issue for you.

**Comment by beeblebrox** [comment]
Brecht, no worries. Thanks for responding. I'm planning to try your suggestion in my original environment.

An interesting find so far though: I could not reproduce the original issue on my Mac with python 3.6.2, sphinx 1.6.6, and rinohtype 0.3.1 with pyenv instead of conda.  I don't think I fully understand the issue still. 

I will dig further, time permitting, and give you another update.

**Comment by paranoidi** [comment]
@brechtm confirmed, stable branch does resolve the issue

**Comment by brechtm** [comment]
@paranoidi Thanks! Closing this issue.
If you're still having problems, @beeblebrox, I can reopen the issue.

**Comment by beeblebrox** [comment]
I am still having the issue after pip installing the stable branch in windows.  I was not able to reproduce the issue on Mac OS using pyenv.  This seems like a windows/conda specific issue.  I don't understand why that would be the case.  Maybe the letter setting information from latex is different on windows and that is causing the issue?

Has anyone tried this on windows with conda? I am using Windows 10 Pro, 64bit.

This is how I installed from stable in a fresh conda environment:
```
(simple_clean) C:\Users\beebl\simple>pip install git+https://github.com/brechtm/rinohtype.git@stable
Collecting git+https://github.com/brechtm/rinohtype.git@stable
  Cloning https://github.com/brechtm/rinohtype.git (to stable) to c:\users\beebl\appdata\local\temp\pip-s4l2937n-build
Requirement already satisfied: setuptools in c:\users\beebl\anaconda3\envs\simple_clean\lib\site-packages (from rinohtype==0.3.2.dev0+1b49aea.dirty20180316)
Requirement already satisfied: pip in c:\users\beebl\anaconda3\envs\simple_clean\lib\site-packages (from rinohtype==0.3.2.dev0+1b49aea.dirty20180316)
Requirement already satisfied: docutils in c:\users\beebl\anaconda3\envs\simple_clean\lib\site-packages (from rinohtype==0.3.2.dev0+1b49aea.dirty20180316)
Collecting recommonmark (from rinohtype==0.3.2.dev0+1b49aea.dirty20180316)
  Using cached recommonmark-0.4.0-py2.py3-none-any.whl
Collecting rinoh-typeface-texgyrecursor>=0.1.1 (from rinohtype==0.3.2.dev0+1b49aea.dirty20180316)
  Using cached rinoh_typeface_texgyrecursor-0.1.1-py3-none-any.whl
Collecting rinoh-typeface-texgyreheros>=0.1.1 (from rinohtype==0.3.2.dev0+1b49aea.dirty20180316)
  Using cached rinoh_typeface_texgyreheros-0.1.1-py3-none-any.whl
Collecting rinoh-typeface-texgyrepagella>=0.1.1 (from rinohtype==0.3.2.dev0+1b49aea.dirty20180316)
  Using cached rinoh_typeface_texgyrepagella-0.1.1-py3-none-any.whl
Collecting rinoh-typeface-dejavuserif (from rinohtype==0.3.2.dev0+1b49aea.dirty20180316)
  Using cached rinoh_typeface_dejavuserif-0.1.1-py3-none-any.whl
Collecting commonmark<=0.5.4 (from recommonmark->rinohtype==0.3.2.dev0+1b49aea.dirty20180316)
Installing collected packages: commonmark, recommonmark, rinoh-typeface-texgyrecursor, rinoh-typeface-texgyreheros, rinoh-typeface-texgyrepagella, rinoh-typeface-dejavuserif, rinohtype
  Running setup.py install for rinohtype ... done
Successfully installed commonmark-0.5.4 recommonmark-0.4.0 rinoh-typeface-dejavuserif-0.1.1 rinoh-typeface-texgyrecursor-0.1.1 rinoh-typeface-texgyreheros-0.1.1 rinoh-typeface-texgyrepagella-0.1.1 rinohtype-0.3.2.dev0+1b49aea.dirty20180316
```

This is the error I received:
```
(simple_clean) C:\Users\beebl\simple>make rinoh
Running Sphinx v1.7.1
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [rinoh]: all documents
'rinoh_logo' config variable not set, automatically converting from 'latex_logo'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'

Exception occurred:
  File "c:\users\beebl\anaconda3\envs\simple_clean\lib\site-packages\rinoh\frontend\sphinx\__init__.py", line 319, in default_paper_size
    return dict(a4paper=A4, letterpaper=LETTER)[latex_paper_size]
KeyError: 'a4'
The full traceback has been saved in C:\Users\beebl\AppData\Local\Temp\sphinx-err-kmkh4xvp.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

The output of the log is the same as I already posted.

I tried with a different version of python, just in case.  Also with Sphinx 1.7.1.  For the sake of being thural, here is my full conda environment:
````
(simple_clean) C:\Users\beebl\simple>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\beebl\Anaconda3  (writable)
    default environment : C:\Users\beebl\Anaconda3\envs\simple_clean
       envs directories : C:\Users\beebl\Anaconda3\envs
                          C:\Users\beebl\AppData\Local\conda\conda\envs
                          C:\Users\beebl\.conda\envs
          package cache : C:\Users\beebl\Anaconda3\pkgs
                          C:\Users\beebl\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
          administrator : False

(simple_clean) C:\Users\beebl\simple>conda list
# packages in environment at C:\Users\beebl\Anaconda3\envs\simple_clean:
#
alabaster                 0.7.10                    <pip>
Babel                     2.5.3                     <pip>
certifi                   2018.1.18                py35_0
chardet                   3.0.4                     <pip>
colorama                  0.3.9                     <pip>
CommonMark                0.5.4                     <pip>
docutils                  0.14                      <pip>
idna                      2.6                       <pip>
imagesize                 1.0.0                     <pip>
Jinja2                    2.10                      <pip>
MarkupSafe                1.0                       <pip>
packaging                 17.1                      <pip>
pip                       9.0.1                    py35_5
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    3.5.5                h0c2934d_1
pytz                      2018.3                    <pip>
recommonmark              0.4.0                     <pip>
requests                  2.18.4                    <pip>
rinoh-typeface-dejavuserif 0.1.1                     <pip>
rinoh-typeface-texgyrecursor 0.1.1                     <pip>
rinoh-typeface-texgyreheros 0.1.1                     <pip>
rinoh-typeface-texgyrepagella 0.1.1                     <pip>
rinohtype                 0.3.2.dev0+1b49aea.dirty20180316           <pip>
setuptools                38.5.1                   py35_0
six                       1.11.0                    <pip>
snowballstemmer           1.2.1                     <pip>
Sphinx                    1.7.1                     <pip>
sphinxcontrib-websupport  1.0.1                     <pip>
urllib3                   1.22                      <pip>
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wheel                     0.30.0           py35h38a90bc_1
wincertstore              0.2              py35hfebbdb8_0
````

![](https://i.gyazo.com/e55478570b17e020b6c05063b53e39ea.png)

**Comment by beeblebrox** [comment]
I concur, this doesn't seem to be an issue in stable.  Thanks everyone.

I deleted my last update because my re-test environment was invalid due to artifacts from previous experimentation.

**Comment by kacann** [comment]
Hi - how do I get the stable branch?
